DTM_Nigeria/Controllers/WInformantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTM_Nigeria.Models;
using System.Web.Script.Serialization;

namespace DTM_Nigeria.Controllers
{
    public class WInformantController : Controller
    {
        iomdtmEntities _entity = new iomdtmEntities();
        public int ward_profile_id;

        SessionPath sesspath = new SessionPath();
        //
        // GET: /WInformant/

        public ActionResult Index(int? id)
        {
            ViewBag.Active = "B1F";

            if (id != null)
            {
                setSession(id ?? 0);
                ward_profile_id = id ?? 0;
            }
            else
                getSession();


            var infs = from c in _entity.iom_b2f_informants
                       where c.ward_profile_id == ward_profile_id
                       orderby c.created_by descending
                       select c;


            return View(infs);
        }

        public void setSession(int id)
        {
            //sesspath.setSession((SessionPath)Session["SessionPath"]);
            HttpCookie aCookie = Request.Cookies["SessionPath"];

            if (aCookie != null)
            {
                SessionPath sesspath = (SessionPath)(new JavaScriptSerializer().Deserialize(aCookie.Value, typeof(SessionPath)));

                sesspath.b2f_profile = id;

                //ViewBag.LgaInfo = sesspath.getLgaInfo();
                ViewBag.WardInfo = sesspath.getWardInfo();

                string sesspath_serial = new JavaScriptSerializer().Serialize(sesspath);

                var cookie = new HttpCookie("SessionPath", sesspath_serial);
                HttpContext.Response.Cookies.Add(cookie);
            }
            //sesspath.b2f_profile = id;

            //ViewBag.WardInfo = sesspath.getWardInfo();

            //Session["SessionPath"] = sesspath;

            //Session["ward_profile_id"] = id;
        }

        public void getSession()
        {
            //sesspath.setSession((SessionPath)Session["SessionPath"]);
            HttpCookie aCookie = Request.Cookies["SessionPath"];

            if (aCookie != null)
            {
                SessionPath sesspath = (SessionPath)(new JavaScriptSerializer().Deserialize(aCookie.Value, typeof(SessionPath)));

                ward_profile_id = sesspath.b2f_profile ?? 0;

                ViewBag.WardInfo = sesspath.getWardInfo();
                //   ward_profile_id = (int)Session["ward_p
            }

            //ward_profile_id = sesspath.b2f_profile ?? 0;

            //ViewBag.WardInfo = sesspath.getWardInfo();
            ////   ward_profile_id = (int)Session["ward_profile_id"];


        }

        //public void setSession(int id)
        //{
        //    Session["ward_profile_id"] = id;
        //}

        //public void getSession()
        //{
        //    ward_profile_id = (int)Session["ward_profile_id"];


        //}

        //
        // GET: /WInformant/Details/5

        public ActionResult Details(int id)
        {
            ViewBag.Active = "B1F";

            var inf = (from c in _entity.iom_b2f_informants
                       where c.id == id
                       select c).FirstOrDefault();
            return View(inf);
        }

        public void setViewBags()
        {
            getSession();
            ViewBag.InformantType = new SelectList(_entity.lkp_Informant_Type, "id", "informant");
        }

        public iom_informants findInfB2F(iom_informants inf)
        {
            iom_informants inf_ = _entity.iom_informants.Where(x => x.name.Equals(inf.name) && x.sex.Equals(inf.sex) && x.type == inf.type).FirstOrDefault();
            if (inf_ != null) inf_.notEmpty = true;
            return inf_ == null ? inf : inf_;
        }


        public JsonResult GetInfsNames(string term)
        {
            List<string> infs;

            infs = _entity.iom_informants.Where(x => x.name.Contains(term))
                .Select(y => y.name).Distinct().ToList();

            return Json(infs, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /WInformant/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Active = "B1F";

            setViewBags();
            InfB2F inf = new InfB2F();
            return View(inf);
        } 

        //
        // POST: /WInformant/Create

        [HttpPost]
        public ActionResult Create(InfB2F informant)
        {
            ViewBag.Active = "B1F";

            setViewBags();

            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here

                    iom_b2f_informants inf = informant.pinf;

                    inf.iom_informants = findInfB2F(informant.inf);

                    inf.ward_profile_id = ward_profile_id;

                    inf.created_by = User.Identity.Name;
                    inf.updated_by = User.Identity.Name;

                    DateTime tmp = DateTime.Now;
                    inf.create_time = tmp;
                    inf.update_time = tmp;

                    _entity.iom_b2f_informants.Add(inf);// Add(inf);
                    _entity.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Exception = "* Operation failed!";

                    return View(informant);
                }
            }

            return View(informant);
        }
        
        //
        // GET: /WInformant/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            ViewBag.Active = "B1F";

            setViewBags();

            var inf = (from c in _entity.iom_b2f_informants
                       where c.id == id
                       select c).FirstOrDefault();

            return View(new InfB2F(inf));
        }

        //
        // POST: /WInformant/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, InfB2F informant)
        {
            ViewBag.Active = "B1F";

            setViewBags();

            var inf = (from c in _entity.iom_b2f_informants
                       where c.id == id
                       select c).FirstOrDefault();

            if (inf != null)
            {
                try
                {
                    // TODO: Add update logic here
                    DateTime tmp = DateTime.Now;

                    inf.update_time = tmp;
                    inf.updated_by = User.Identity.Name;

                    inf.iom_informants = findInfB2F(informant.inf);

                    inf.contact_details = informant.pinf.contact_details;

                    UpdateModel(inf);
                    _entity.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Exception = "* Operation failed!";

                    return View(informant);
                }
            }

            return View(informant);
        }

        //
        // GET: /WInformant/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            ViewBag.Active = "B1F";

            var inf = (from c in _entity.iom_b2f_informants
                       where c.id == id
                       select c).FirstOrDefault();

            if (inf != null)
            {
                return View(inf);
            }

            return RedirectToAction("Index");
        }

        //
        // POST: /WInformant/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            ViewBag.Active = "B1F";

            var inf = (from c in _entity.iom_b2f_informants
                       where c.id == id
                       select c).FirstOrDefault();

            if (inf != null)
            {
                try
                {
                    // TODO: Add delete logic here
                    _entity.iom_b2f_informants.Remove(inf);// Remove(inf);

                    _entity.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Exception = "* Operation failed!";

                    return View(inf);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

DTM_Nigeria/Views/WInformant/Create.cshtml
@model DTM_Nigeria.Models.InfB2F

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create informant/B2F</h2>
<h3>@ViewBag.WardInfo</h3>

@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<link href="../../Content/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="../../Scripts/jquery-ui.js" type="text/javascript"></script>

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(function () {

        $("#inf_name").autocomplete({
            source: '@Url.Action("GetInfsNames","WInformant")'

        });

    });
</script>


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

List<SelectListItem> sex = new List<SelectListItem>();

sex.Add(new SelectListItem { Text = "Male", Value = "M" });
sex.Add(new SelectListItem { Text = "Female", Value = "F" });
sex.Add(new SelectListItem { Text = "N/A", Value = "x" });
    
    
    <fieldset>
        <legend>informant information</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.inf.name)
        </div>
        <div class="editor-field">
        @using (Html.BeginForm())
        { 
            @Html.EditorFor(model => model.inf.name)
            @Html.ValidationMessageFor(model => model.inf.name)
        }
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.inf.type)
        </div>

        <div class="editor-field">
            @Html.DropDownListFor(model => model.inf.type, (SelectList)ViewBag.InformantType, "[Select type]")
            @Html.ValidationMessageFor(model => model.inf.type)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.inf.sex)
        </div>

         <div class="editor-field">
            @Html.DropDownListFor(model => model.inf.sex, sex, "[Select sex]")
            @Html.ValidationMessageFor(model => model.inf.sex)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pinf.contact_details)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pinf.contact_details)
            @Html.ValidationMessageFor(model => model.pinf.contact_details)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>

DTM_Nigeria/Views/WInformant/Delete.cshtml
@model DTM_Nigeria.Models.iom_b2f_informants

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete informant/B2F</h2>


@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>
}

<h3>Are you sure you want to delete this?</h3>


<fieldset>
    <legend>informant information</legend>

   <div class="display-label">names</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.iom_informants.name)
    </div>

    <div class="display-label">type</div>
    <div class="display-field">
        @*Html.DisplayFor(model => model.type)*@
        @Model.iom_informants.lkp_Informant_Type.informant
    </div>

    <div class="display-label">sex</div>
    <div class="display-field">
        @Model.iom_informants.lkp_Sex.sex
    </div>

    <div class="display-label">contact_details</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.contact_details)
    </div>

    <div class="display-label">created_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.created_by)
    </div>

    <div class="display-label">create_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.create_time)
    </div>

    <div class="display-label">updated_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.updated_by)
    </div>

    <div class="display-label">update_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_time)
    </div>   

   
</fieldset>


@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

DTM_Nigeria/Views/WInformant/Details.cshtml
@model DTM_Nigeria.Models.iom_b2f_informants

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Informant Details/B2F</h2>


<fieldset>
    <legend>informant information</legend>

    <div class="display-label">names</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.iom_informants.name)
    </div>

    <div class="display-label">type</div>
    <div class="display-field">
        @*Html.DisplayFor(model => model.type)*@
        @Model.iom_informants.lkp_Informant_Type.informant
    </div>

    <div class="display-label">sex</div>
    <div class="display-field">
        @Model.iom_informants.lkp_Sex.sex
    </div>

    <div class="display-label">contact_details</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.contact_details)
    </div>

    <div class="display-label">created_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.created_by)
    </div>

    <div class="display-label">create_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.create_time)
    </div>

    <div class="display-label">updated_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.updated_by)
    </div>

    <div class="display-label">update_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_time)
    </div>

</fieldset>


<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DTM_Nigeria/Views/WInformant/Edit.cshtml
@model DTM_Nigeria.Models.InfB2F

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit informant/B2F</h2>
<h3>@ViewBag.WardInfo</h3>

@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<link href="../../Content/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="../../Scripts/jquery-ui.js" type="text/javascript"></script>

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(function () {

        $("#inf_name").autocomplete({
            source: '@Url.Action("GetInfsNames","WInformant")'

        });

    });
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

List<SelectListItem> sex = new List<SelectListItem>();

sex.Add(new SelectListItem { Text = "Male", Value = "M" });
sex.Add(new SelectListItem { Text = "Female", Value = "F" });
sex.Add(new SelectListItem { Text = "N/A", Value = "x" });
    
    
    <fieldset>
        <legend>informant information</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.inf.name)
        </div>
        <div class="editor-field">
        @using (Html.BeginForm())
        { 
            @Html.EditorFor(model => model.inf.name)
            @Html.ValidationMessageFor(model => model.inf.name)
        }
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.inf.type)
        </div>

        <div class="editor-field">
            @Html.DropDownListFor(model => model.inf.type, (SelectList)ViewBag.InformantType, "[Select type]")
            @Html.ValidationMessageFor(model => model.inf.type)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.inf.sex)
        </div>

         <div class="editor-field">
            @Html.DropDownListFor(model => model.inf.sex, sex, "[Select sex]")
            @Html.ValidationMessageFor(model => model.inf.sex)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pinf.contact_details)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pinf.contact_details)
            @Html.ValidationMessageFor(model => model.pinf.contact_details)
        </div>


        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

DTM_Nigeria/Views/WInformant/Index.cshtml
@model IEnumerable<DTM_Nigeria.Models.iom_b2f_informants>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Key informant/B2F</h2>
<h3>@ViewBag.WardInfo</h3>

<p>
    @Html.ActionLink("Add new informant", "Create")
</p>

@if (Model.Count() > 0)
{
<table>
    <tr>
        <th>
            names
        </th>
        <th>
            type
        </th>
        <th>
            sex
        </th>
        <th>
            contact_details
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.iom_informants.name)
        </td>
        <td>
            @*Html.DisplayFor(modelItem => item.type)*@
            @item.iom_informants.lkp_Informant_Type.informant
        </td>
        <td>
            @item.iom_informants.lkp_Sex.sex
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contact_details)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>
}
else
{ 
<b>No data</b>
}


<p>
    @Html.ActionLink("Back to B2F", "Index", "B2F")
</p>