DTM_Nigeria/Controllers/WorgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTM_Nigeria.Models;
using System.Web.Script.Serialization;

namespace DTM_Nigeria.Controllers
{
    public class WorgController : Controller
    {
        iomdtmEntities _entity = new iomdtmEntities();
        public int ward_profile_id;

        SessionPath sesspath = new SessionPath();
        //
        // GET: /Worg/

        public ActionResult Index(int? id)
        {
            ViewBag.Active = "B1F";

            if (id != null)
            {
                setSession(id ?? 0);
                ward_profile_id = id ?? 0;
            }
            else
                getSession();


            var orgs = from c in _entity.iom_b2f_organizations_assisting
                       where c.ward_profile_id == ward_profile_id
                       orderby c.created_by descending
                       select c;


            return View(orgs);
        }

        public void setSession(int id)
        {
            //sesspath.setSession((SessionPath)Session["SessionPath"]);

            HttpCookie aCookie = Request.Cookies["SessionPath"];

            if (aCookie != null)
            {
                SessionPath sesspath = (SessionPath)(new JavaScriptSerializer().Deserialize(aCookie.Value, typeof(SessionPath)));

                sesspath.b2f_profile = id;

                //ViewBag.LgaInfo = sesspath.getLgaInfo();
                ViewBag.WardInfo = sesspath.getWardInfo();

                string sesspath_serial = new JavaScriptSerializer().Serialize(sesspath);

                var cookie = new HttpCookie("SessionPath", sesspath_serial);
                HttpContext.Response.Cookies.Add(cookie);
            }

            //sesspath.b2f_profile = id;

            ////ViewBag.LgaInfo = sesspath.getLgaInfo();
            //ViewBag.WardInfo = sesspath.getWardInfo();

            //Session["SessionPath"] = sesspath;

            //Session["ward_profile_id"] = id;
        }

        public void getSession()
        {
            //sesspath.setSession((SessionPath)Session["SessionPath"]);
            HttpCookie aCookie = Request.Cookies["SessionPath"];

            if (aCookie != null)
            {
                SessionPath sesspath = (SessionPath)(new JavaScriptSerializer().Deserialize(aCookie.Value, typeof(SessionPath)));

                ward_profile_id = sesspath.b2f_profile ?? 0;

                //ViewBag.LgaInfo = sesspath.getLgaInfo();
                ViewBag.WardInfo = sesspath.getWardInfo();
            }
            //ward_profile_id = sesspath.b2f_profile??0;

            ////ViewBag.LgaInfo = sesspath.getLgaInfo();
            //ViewBag.WardInfo = sesspath.getWardInfo();
         //   ward_profile_id = (int)Session["ward_profile_id"];


        }

        //
        // GET: /Worg/Details/5

        public ActionResult Details(int id)
        {
            ViewBag.Active = "B1F";

            var org = (from c in _entity.iom_b2f_organizations_assisting
                       where c.id == id
                       select c).FirstOrDefault();
            return View(org);
        }

        public void setViewBags()
        {
            getSession();
            ViewBag.OrgType = new SelectList(_entity.lkp_Organization, "id", "organization");
            ViewBag.AssType = new SelectList(_entity.lkp_assistance_type, "id", "assistance_type");
        }

        public iom_organizations findOrgB2F(iom_organizations org)
        {
            iom_organizations org_ = _entity.iom_organizations.Where(x => x.name.Equals(org.name)).FirstOrDefault();

            return org_ == null ? org : org_;
        }


        [HttpPost]
        public JsonResult GetOrgType(string o_name)
        {
            //var r_tel = new SelectList( _entity.iom_researchers.Where(x => x.researcher_name.Equals(r_name)), "researcher_tel", "researcher_tel").FirstOrDefault();

            var o_type = _entity.iom_organizations.Where(x => x.name.Equals(o_name)).Select(y => y.type).FirstOrDefault();


            return Json(o_type, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetOrgsNames(string term)
        {
            List<string> orgs;

            orgs = _entity.iom_organizations.Where(x => x.name.Contains(term))
                .Select(y => y.name).ToList();

            return Json(orgs, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Worg/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Active = "B1F";

            setViewBags(); 
            OrgB2F porg = new OrgB2F();
            return View(porg);
        } 

        //
        // POST: /Worg/Create

        [HttpPost]
        public ActionResult Create(OrgB2F my_org)
        {
            ViewBag.Active = "B1F";

            setViewBags();

            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add insert logic here
                    iom_b2f_organizations_assisting org_ = my_org.porg;

                    org_.iom_organizations = findOrgB2F(my_org.org);
                    org_.iom_organizations.type = my_org.org.type;

                    org_.ward_profile_id = ward_profile_id;

                    org_.created_by = User.Identity.Name;
                    org_.updated_by = User.Identity.Name;

                    DateTime tmp = DateTime.Now;
                    org_.create_time = tmp;
                    org_.update_time = tmp;

                    _entity.iom_b2f_organizations_assisting.Add(org_);//Add(org_);
                    _entity.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Exception = "* Operation failed!";

                    return View(my_org);
                }
            }

            return View(my_org);
        }
        
        //
        // GET: /Worg/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            ViewBag.Active = "B1F";

            setViewBags();

            var org = (from c in _entity.iom_b2f_organizations_assisting
                       where c.id == id
                       select c).FirstOrDefault();

            return View(new OrgB2F(org));
        }

        //
        // POST: /Worg/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, OrgB2F my_org)
        {
            ViewBag.Active = "B1F";

            setViewBags();

            var org = (from c in _entity.iom_b2f_organizations_assisting
                       where c.id == id
                       select c).FirstOrDefault();
            if (org != null)
            {
                try
                {
                    // TODO: Add update logic here
                    DateTime tmp = DateTime.Now;
                    org.update_time = tmp;
                    org.updated_by = User.Identity.Name;

                    org.iom_organizations = findOrgB2F(my_org.org);

                    org.iom_organizations.type = my_org.org.type;

                    org.contact_person = my_org.porg.contact_person;

                    org.assistance_type = my_org.porg.assistance_type;

                    UpdateModel(org);
                    _entity.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Exception = "* Operation failed!";

                    return View(my_org);
                }
            }

            return View(my_org);
        }

        //
        // GET: /Worg/Delete/5
           [Authorize]
        public ActionResult Delete(int id)
        {
            ViewBag.Active = "B1F";

            var org = (from c in _entity.iom_b2f_organizations_assisting
                       where c.id == id
                       select c).FirstOrDefault();

            if (org != null)
            {
                return View(org);
            }

            return RedirectToAction("Index");
        }

        //
        // POST: /Worg/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            ViewBag.Active = "B1F";

            var org = (from c in _entity.iom_b2f_organizations_assisting
                       where c.id == id
                       select c).FirstOrDefault();

            if (org != null)
            {
                try
                {
                    // TODO: Add delete logic here
                    _entity.iom_b2f_organizations_assisting.Remove(org);//Remove(org);

                    _entity.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Exception = "* Operation failed!";

                    return View(org);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

DTM_Nigeria/Views/Worg/Create.cshtml
@model DTM_Nigeria.Models.OrgB2F

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create organization/B2F</h2>
<h3>@ViewBag.WardInfo</h3>

@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<link href="../../Content/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="../../Scripts/jquery-ui.js" type="text/javascript"></script>

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(function () {

        $("#org_name").autocomplete({
            source: '@Url.Action("GetOrgsNames","Worg")',
            focus: function (event, ui) {
                $("#org_name").val(ui.item.label);
                return false;
            },
            select: function (event, ui) {

                $.ajax({
                    url: "/Worg/GetOrgType",
                    type: 'POST',
                    data: { o_name: ui.item.label },
                    success: function (org) {
                        var $telTxtBox = $('#org_type');
                        $telTxtBox.val(org.toString());
                    },
                    error: function (xhr) { alert("error!!"); }
                });

            }
        }
        );

    });
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>organization information</legend>

      

        <div class="editor-label">
            Organization name
        </div>
        <div class="editor-field">
        @using (Html.BeginForm())
        { 
            @Html.EditorFor(model => model.org.name)
            @Html.ValidationMessageFor(model => model.org.name)
        }
        </div>


        <div class="editor-label">
            Organization type
        </div>

        <div class="editor-field">
            @Html.DropDownListFor(model => model.org.type, (SelectList)ViewBag.OrgType, "[Select organization type]")
            @Html.ValidationMessageFor(model => model.org.type)
        </div>

        <div class="editor-label">
            Assistance type
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.porg.assistance_type, (SelectList)ViewBag.AssType, "[Select assistance type]")
            @Html.ValidationMessageFor(model => model.porg.assistance_type)
        </div>

        <div class="editor-label">
            Contact person
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.porg.contact_person)
            @Html.ValidationMessageFor(model => model.porg.contact_person)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}


<div>
    @Html.ActionLink("Back to organizations List/B2F", "Index")
</div>

DTM_Nigeria/Views/Worg/Delete.cshtml
@model DTM_Nigeria.Models.iom_b2f_organizations_assisting

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete organization/B2F</h2>

@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>
}

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>organization information</legend>

     <div class="display-label">name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.iom_organizations.name)
    </div>

    <div class="display-label">type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.iom_organizations.lkp_Organization.organization)
    </div>

    <div class="display-label">assistance_type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.lkp_assistance_type.assistance_type)
    </div>

    <div class="display-label">contact_person</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.contact_person)
    </div>

    <div class="display-label">created_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.created_by)
    </div>

    <div class="display-label">create_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.create_time)
    </div>

    <div class="display-label">updated_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.updated_by)
    </div>

    <div class="display-label">update_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_time)
    </div>

</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to organizations List/B2F", "Index")
    </p>
}

DTM_Nigeria/Views/Worg/Details.cshtml
@model DTM_Nigeria.Models.iom_b2f_organizations_assisting

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Organization Details/B2F</h2>

<fieldset>
    <legend>organization information</legend>


    <div class="display-label">name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.iom_organizations.name)
    </div>

    <div class="display-label">type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.iom_organizations.lkp_Organization.organization)
    </div>

    <div class="display-label">assistance_type</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.lkp_assistance_type.assistance_type)
    </div>

    <div class="display-label">contact_person</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.contact_person)
    </div>

    <div class="display-label">created_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.created_by)
    </div>

    <div class="display-label">create_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.create_time)
    </div>

    <div class="display-label">updated_by</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.updated_by)
    </div>

    <div class="display-label">update_time</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.update_time)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to organizations List/B2F", "Index")
</p>

DTM_Nigeria/Views/Worg/Edit.cshtml
@model DTM_Nigeria.Models.OrgB2F

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit organization/B2F</h2>
<h3>@ViewBag.WardInfo</h3>

@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<link href="../../Content/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="../../Scripts/jquery-ui.js" type="text/javascript"></script>

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(function () {

        $("#org_name").autocomplete({
            source: '@Url.Action("GetOrgsNames","Worg")',
            focus: function (event, ui) {
                $("#org_name").val(ui.item.label);
                return false;
            },
            select: function (event, ui) {

                $.ajax({
                    url: "/Worg/GetOrgType",
                    type: 'POST',
                    data: { o_name: ui.item.label },
                    success: function (org) {
                        var $telTxtBox = $('#org_type');
                        $telTxtBox.val(org.toString());
                    },
                    error: function (xhr) { alert("error!!"); }
                });

            }
        }
        );

    });
</script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>organization information</legend>

        
      <div class="editor-label">
            Organization name
        </div>
        <div class="editor-field">
         @using (Html.BeginForm())
        { 
            @Html.EditorFor(model => model.org.name)
            @Html.ValidationMessageFor(model => model.org.name)
        }
        </div>


        <div class="editor-label">
            Organization type
        </div>

        <div class="editor-field">
            @Html.DropDownListFor(model => model.org.type, (SelectList)ViewBag.OrgType, "[Select organization type]")
            @Html.ValidationMessageFor(model => model.org.type)
        </div>

        <div class="editor-label">
            Assistance type
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.porg.assistance_type, (SelectList)ViewBag.AssType, "[Select assistance type]")
            @Html.ValidationMessageFor(model => model.porg.assistance_type)
        </div>

        <div class="editor-label">
            Contact person
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.porg.contact_person)
            @Html.ValidationMessageFor(model => model.porg.contact_person)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to organizations List/B2F", "Index")
</div>

DTM_Nigeria/Views/Worg/Index.cshtml
@model IEnumerable<DTM_Nigeria.Models.iom_b2f_organizations_assisting>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Organization assisting IDPs in the Ward/B2F</h2>
<h3>@ViewBag.WardInfo</h3>
<p>
    @Html.ActionLink("Add new organization ", "Create")
</p>

@if(Model.Count()>0){

<table>
    <tr>
        <th>
            name
        </th>
        <th>
            type
        </th>
        <th>
            assistance_type
        </th>
        <th>
            contact_person
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.iom_organizations.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.iom_organizations.lkp_Organization.organization)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lkp_assistance_type.assistance_type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contact_person)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>
}
else
{ 
<b>No data</b>
}
    
    
<p>
    @Html.ActionLink("Back to B2F", "Index", "B2F")
</p>